
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 28 12:21:45 BRT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 20;
  public static final int Divisao = 31;
  public static final int Incremento = 55;
  public static final int FechaCH = 28;
  public static final int Enquanto = 17;
  public static final int Double = 7;
  public static final int If = 11;
  public static final int AbreCO = 25;
  public static final int Id = 50;
  public static final int Void = 8;
  public static final int Maior = 39;
  public static final int Equal = 21;
  public static final int Decremento = 56;
  public static final int Diferente = 43;
  public static final int PulaLinha = 41;
  public static final int AbreCH = 27;
  public static final int Underline = 22;
  public static final int Menor = 38;
  public static final int Else = 12;
  public static final int Constante = 5;
  public static final int Para = 18;
  public static final int Return = 16;
  public static final int Int = 6;
  public static final int AbreP = 23;
  public static final int Float = 10;
  public static final int EOF = 0;
  public static final int And = 49;
  public static final int Not = 35;
  public static final int Printf = 14;
  public static final int error = 1;
  public static final int AspasDuplas = 33;
  public static final int FechaP = 24;
  public static final int Vir = 47;
  public static final int Tab = 42;
  public static final int Recebe = 40;
  public static final int MaiorIgual = 44;
  public static final int Char = 9;
  public static final int Soma = 29;
  public static final int ERROR = 54;
  public static final int Pv = 48;
  public static final int Multiplicacao = 37;
  public static final int Resto = 36;
  public static final int AspasSimples = 32;
  public static final int MenorIgual = 45;
  public static final int Hash = 2;
  public static final int Scanf = 13;
  public static final int String = 52;
  public static final int QuebraLinhaStringError = 53;
  public static final int Lib = 4;
  public static final int Ponto = 46;
  public static final int Numero = 51;
  public static final int ContraBarra = 34;
  public static final int Include = 3;
  public static final int Main = 15;
  public static final int FechaCO = 26;
  public static final int Subtracao = 30;
  public static final int AndAnd = 19;
}

